Feat: ESLint
unlikelystudio/bases pull request #15
Opened 2021-04-08 10:31 UTC by bastienrobert

Add eslint configuration which extends `eslint:recommended` and `plugin:@typescript-eslint/recommended`.

<details>
<summary>Print-configuration rules</summary>
```json
{
  "@typescript-eslint/explicit-module-boundary-types": "off",
  "@typescript-eslint/adjacent-overload-signatures": "error",
  "@typescript-eslint/ban-ts-comment": "error",
  "@typescript-eslint/ban-types": "error",
  "no-array-constructor": "off",
  "@typescript-eslint/no-array-constructor": "error",
  "no-empty-function": "off",
  "@typescript-eslint/no-empty-function": "error",
  "@typescript-eslint/no-empty-interface": "error",
  "@typescript-eslint/no-explicit-any": "warn",
  "@typescript-eslint/no-extra-non-null-assertion": "error",
  "no-extra-semi": "off",
  "@typescript-eslint/no-extra-semi": "error",
  "@typescript-eslint/no-inferrable-types": "error",
  "@typescript-eslint/no-misused-new": "error",
  "@typescript-eslint/no-namespace": "error",
  "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
  "@typescript-eslint/no-non-null-assertion": "warn",
  "@typescript-eslint/no-this-alias": "error",
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "warn",
  "@typescript-eslint/no-var-requires": "error",
  "@typescript-eslint/prefer-as-const": "error",
  "@typescript-eslint/prefer-namespace-keyword": "error",
  "@typescript-eslint/triple-slash-reference": "error",
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-misleading-character-class": "error",
  "no-mixed-spaces-and-tabs": "error",
  "no-new-symbol": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unused-labels": "error",
  "no-useless-catch": "error",
  "no-useless-escape": "error",
  "no-with": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error"
}
```
</details>

2021-04-08 15:02 UTC, raroul commented
@bastienrobert Il faudrait vérifier que les regles eslint ne prennent pas le pas sur les regles prettier.

2021-04-08 15:04 UTC, bastienrobert commented
Actually we need to add Prettier plugin either

2021-04-08 15:17 UTC, baloran commented
Mais par contre n'oubliez pas que la config typescript est important quand on va utiliser un linter comme eslint. Mais que pour le moment il me semble que sur tous les projet next c'est la config typescript de next qui est utilisé et pas celle d'Unlikely. Il faudrait faire un choix pour que le code soit homogene au maximum.

2021-04-08 15:21 UTC, bastienrobert commented
> Mais par contre n'oubliez pas que la config typescript est important quand on va utiliser un linter comme eslint. Mais que pour le moment il me semble que sur tous les projet next c'est la config typescript de next qui est utilisé et pas celle d'Unlikely. Il faudrait faire un choix pour que le code soit homogène au maximum.

Il semble que ce soit fix depuis la [v10.1](https://nextjs.org/blog/next-10-1#support-for-extends-in-tsconfigjson).

2021-04-08 15:23 UTC, baloran commented
> > Mais par contre n'oubliez pas que la config typescript est important quand on va utiliser un linter comme eslint. Mais que pour le moment il me semble que sur tous les projet next c'est la config typescript de next qui est utilisé et pas celle d'Unlikely. Il faudrait faire un choix pour que le code soit homogène au maximum.
> 
> Il semble que ce soit fix depuis la [v10.1](https://nextjs.org/blog/next-10-1#support-for-extends-in-tsconfigjson).

Non mais je parle du tsconfig du projet `jpg-fashion` par exemple. C'est celui de base de next pas d'un qui hérite de @unlikelystudio/bases-typescript.

2021-04-08 15:27 UTC, bastienrobert commented
Ah mais c'est pas un soucis aussi, on extends ici des configs de base, seul `explicit-module-boundary-types` est manuellement désactivé pour conserver les retours implicites des fonctions. A voir à l'utilisation mais je pense que cette configuration peut s'adapter à nos différents projets.

2021-04-08 15:31 UTC, raroul commented
Y'a des regles qui sont liées à react dans eslint:recommended ?

2021-04-08 15:34 UTC, bastienrobert commented
J'ai pas l'impression @raroul : [eslint:recommended](https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js)

2021-04-08 15:38 UTC, raroul commented
> J'ai pas l'impression @raroul : [eslint:recommended](https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js)

Du coup ok pour ajouter `eslint-plugin-react` et `eslint-plugin-react-hooks` ?

2021-04-08 16:45 UTC, bastienrobert commented
Ca devrait être good @raroul

<details>
<summary>Nouvelle liste de règles</summary>

```json
{
    "@typescript-eslint/explicit-module-boundary-types": ["off"],
    "curly": [0],
    "lines-around-comment": [0],
    "max-len": [0],
    "no-confusing-arrow": [0],
    "no-mixed-operators": [0],
    "no-tabs": [0],
    "no-unexpected-multiline": [0],
    "quotes": [0],
    "@typescript-eslint/quotes": [0],
    "babel/quotes": [0],
    "vue/html-self-closing": [0],
    "vue/max-len": [0],
    "array-bracket-newline": ["off"],
    "array-bracket-spacing": ["off"],
    "array-element-newline": ["off"],
    "arrow-parens": ["off"],
    "arrow-spacing": ["off"],
    "block-spacing": ["off"],
    "brace-style": ["off"],
    "comma-dangle": ["off"],
    "comma-spacing": ["off"],
    "comma-style": ["off"],
    "computed-property-spacing": ["off"],
    "dot-location": ["off"],
    "eol-last": ["off"],
    "func-call-spacing": ["off"],
    "function-call-argument-newline": ["off"],
    "function-paren-newline": ["off"],
    "generator-star": ["off"],
    "generator-star-spacing": ["off"],
    "implicit-arrow-linebreak": ["off"],
    "indent": ["off"],
    "jsx-quotes": ["off"],
    "key-spacing": ["off"],
    "keyword-spacing": ["off"],
    "linebreak-style": ["off"],
    "multiline-ternary": ["off"],
    "newline-per-chained-call": ["off"],
    "new-parens": ["off"],
    "no-arrow-condition": ["off"],
    "no-comma-dangle": ["off"],
    "no-extra-parens": ["off"],
    "no-extra-semi": ["off"],
    "no-floating-decimal": ["off"],
    "no-mixed-spaces-and-tabs": ["off"],
    "no-multi-spaces": ["off"],
    "no-multiple-empty-lines": ["off"],
    "no-reserved-keys": ["off"],
    "no-space-before-semi": ["off"],
    "no-trailing-spaces": ["off"],
    "no-whitespace-before-property": ["off"],
    "no-wrap-func": ["off"],
    "nonblock-statement-body-position": ["off"],
    "object-curly-newline": ["off"],
    "object-curly-spacing": ["off"],
    "object-property-newline": ["off"],
    "one-var-declaration-per-line": ["off"],
    "operator-linebreak": ["off"],
    "padded-blocks": ["off"],
    "quote-props": ["off"],
    "rest-spread-spacing": ["off"],
    "semi": ["off"],
    "semi-spacing": ["off"],
    "semi-style": ["off"],
    "space-after-function-name": ["off"],
    "space-after-keywords": ["off"],
    "space-before-blocks": ["off"],
    "space-before-function-paren": ["off"],
    "space-before-function-parentheses": ["off"],
    "space-before-keywords": ["off"],
    "space-in-brackets": ["off"],
    "space-in-parens": ["off"],
    "space-infix-ops": ["off"],
    "space-return-throw-case": ["off"],
    "space-unary-ops": ["off"],
    "space-unary-word-ops": ["off"],
    "switch-colon-spacing": ["off"],
    "template-curly-spacing": ["off"],
    "template-tag-spacing": ["off"],
    "unicode-bom": ["off"],
    "wrap-iife": ["off"],
    "wrap-regex": ["off"],
    "yield-star-spacing": ["off"],
    "@typescript-eslint/brace-style": ["off"],
    "@typescript-eslint/comma-dangle": ["off"],
    "@typescript-eslint/comma-spacing": ["off"],
    "@typescript-eslint/func-call-spacing": ["off"],
    "@typescript-eslint/indent": ["off"],
    "@typescript-eslint/keyword-spacing": ["off"],
    "@typescript-eslint/member-delimiter-style": ["off"],
    "@typescript-eslint/no-extra-parens": ["off"],
    "@typescript-eslint/no-extra-semi": ["off"],
    "@typescript-eslint/object-curly-spacing": ["off"],
    "@typescript-eslint/semi": ["off"],
    "@typescript-eslint/space-before-function-paren": ["off"],
    "@typescript-eslint/space-infix-ops": ["off"],
    "@typescript-eslint/type-annotation-spacing": ["off"],
    "babel/object-curly-spacing": ["off"],
    "babel/semi": ["off"],
    "flowtype/boolean-style": ["off"],
    "flowtype/delimiter-dangle": ["off"],
    "flowtype/generic-spacing": ["off"],
    "flowtype/object-type-curly-spacing": ["off"],
    "flowtype/object-type-delimiter": ["off"],
    "flowtype/semi": ["off"],
    "flowtype/space-after-type-colon": ["off"],
    "flowtype/space-before-generic-bracket": ["off"],
    "flowtype/space-before-type-colon": ["off"],
    "flowtype/union-intersection-spacing": ["off"],
    "react/jsx-child-element-spacing": ["off"],
    "react/jsx-closing-bracket-location": ["off"],
    "react/jsx-closing-tag-location": ["off"],
    "react/jsx-curly-newline": ["off"],
    "react/jsx-curly-spacing": ["off"],
    "react/jsx-equals-spacing": ["off"],
    "react/jsx-first-prop-new-line": ["off"],
    "react/jsx-indent": ["off"],
    "react/jsx-indent-props": ["off"],
    "react/jsx-max-props-per-line": ["off"],
    "react/jsx-newline": ["off"],
    "react/jsx-one-expression-per-line": ["off"],
    "react/jsx-props-no-multi-spaces": ["off"],
    "react/jsx-tag-spacing": ["off"],
    "react/jsx-wrap-multilines": ["off"],
    "standard/array-bracket-even-spacing": ["off"],
    "standard/computed-property-even-spacing": ["off"],
    "standard/object-curly-even-spacing": ["off"],
    "unicorn/empty-brace-spaces": ["off"],
    "unicorn/no-nested-ternary": ["off"],
    "unicorn/number-literal-case": ["off"],
    "vue/array-bracket-newline": ["off"],
    "vue/array-bracket-spacing": ["off"],
    "vue/arrow-spacing": ["off"],
    "vue/block-spacing": ["off"],
    "vue/block-tag-newline": ["off"],
    "vue/brace-style": ["off"],
    "vue/comma-dangle": ["off"],
    "vue/comma-spacing": ["off"],
    "vue/comma-style": ["off"],
    "vue/dot-location": ["off"],
    "vue/func-call-spacing": ["off"],
    "vue/html-closing-bracket-newline": ["off"],
    "vue/html-closing-bracket-spacing": ["off"],
    "vue/html-end-tags": ["off"],
    "vue/html-indent": ["off"],
    "vue/html-quotes": ["off"],
    "vue/key-spacing": ["off"],
    "vue/keyword-spacing": ["off"],
    "vue/max-attributes-per-line": ["off"],
    "vue/multiline-html-element-content-newline": ["off"],
    "vue/mustache-interpolation-spacing": ["off"],
    "vue/no-extra-parens": ["off"],
    "vue/no-multi-spaces": ["off"],
    "vue/no-spaces-around-equal-signs-in-attribute": ["off"],
    "vue/object-curly-newline": ["off"],
    "vue/object-curly-spacing": ["off"],
    "vue/object-property-newline": ["off"],
    "vue/operator-linebreak": ["off"],
    "vue/script-indent": ["off"],
    "vue/singleline-html-element-content-newline": ["off"],
    "vue/space-in-parens": ["off"],
    "vue/space-infix-ops": ["off"],
    "vue/space-unary-ops": ["off"],
    "vue/template-curly-spacing": ["off"],
    "indent-legacy": ["off"],
    "no-spaced-func": ["off"],
    "react/jsx-space-before-closing": ["off"],
    "react-hooks/rules-of-hooks": ["error"],
    "react-hooks/exhaustive-deps": ["warn"],
    "react/display-name": [2],
    "react/jsx-key": [2],
    "react/jsx-no-comment-textnodes": [2],
    "react/jsx-no-duplicate-props": [2],
    "react/jsx-no-target-blank": [2],
    "react/jsx-no-undef": [2],
    "react/jsx-uses-react": [2],
    "react/jsx-uses-vars": [2],
    "react/no-children-prop": [2],
    "react/no-danger-with-children": [2],
    "react/no-deprecated": [2],
    "react/no-direct-mutation-state": [2],
    "react/no-find-dom-node": [2],
    "react/no-is-mounted": [2],
    "react/no-render-return-value": [2],
    "react/no-string-refs": [2],
    "react/no-unescaped-entities": [2],
    "react/no-unknown-property": [2],
    "react/no-unsafe": [0],
    "react/prop-types": [2],
    "react/react-in-jsx-scope": [2],
    "react/require-render-return": [2],
    "@typescript-eslint/adjacent-overload-signatures": ["error"],
    "@typescript-eslint/ban-ts-comment": ["error"],
    "@typescript-eslint/ban-types": ["error"],
    "no-array-constructor": ["off"],
    "@typescript-eslint/no-array-constructor": ["error"],
    "no-empty-function": ["off"],
    "@typescript-eslint/no-empty-function": ["error"],
    "@typescript-eslint/no-empty-interface": ["error"],
    "@typescript-eslint/no-explicit-any": ["warn"],
    "@typescript-eslint/no-extra-non-null-assertion": ["error"],
    "@typescript-eslint/no-inferrable-type [...]

2021-06-21 10:15 UTC, baloran requested changes

2021-06-21 10:15 UTC, baloran commented on packages/eslint/readme.md
> +npx install-peerdeps -D @10up/eslint-config
il faut changer le repo il me sembe

2021-06-21 10:15 UTC, baloran commented on packages/eslint/readme.md
> +npx install-peerdeps -D -Y @10up/eslint-config
il faut changer le repo là aussi

2021-06-21 10:15 UTC, baloran commented on packages/eslint/readme.md
> +  "extends": "@unlikelystudio/eslint-config"
Pas besoins de mettre `eslint-config` eslint le fait tout seul il me semble.

```
{
"extends": "@unlikelystudio"
}
```

2021-06-21 10:15 UTC, baloran commented on packages/eslint/package.json
> +  }
il faudrait mettre à jour les dependancies

2021-06-21 12:14 UTC, baloran approved these changes

2021-06-21 12:16 UTC, merged